version: '3.2'
services:
    api_order:
        build: .
        ports:
            - "8000:8000"
        environment:
            POSTGRES_SERVER: postgres_order
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: app
            USER_API_URL: http://wiremock_order:8080/users
            USER_API_TIMEOUT: 0.5
            REDIS_URL: redis://redis_order:6379

    redis_order:
        image: sickp/alpine-redis:3.2.2
        ports:
            - "6379:6379"

    elasticsearch_order:
        image: elasticsearch:8.8.1
        environment:
            - discovery.type=single-node
            - ES_JAVA_OPTS=-Xms1g -Xmx1g
            - xpack.security.enabled=false
        ports:
            - "9200:9200"

    wiremock_order:
        image: wiremock/wiremock:2.35.0
        volumes:
            - ./wiremock:/home/wiremock
        ports:
            - "8443:8080"
